# Generated by Django 2.2 on 2021-02-18 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='media/boletas')),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identidad', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('Sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=15)),
                ('telefono', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=150)),
                ('direccion', models.CharField(max_length=650)),
                ('foto', models.ImageField(upload_to='media/candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Aldea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Municipio')),
            ],
        ),
    ]
