# Generated by Django 2.2 on 2021-02-18 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='numero',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
