# Generated by Django 2.2 on 2021-02-20 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_boleta_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Candidato'),
            preserve_default=False,
        ),
    ]
