# Generated by Django 2.2 on 2021-02-20 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_boleta_candidato'),
    ]

    operations = [
        migrations.AddField(
            model_name='boleta',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Municipio'),
            preserve_default=False,
        ),
    ]
