# Generated by Django 2.2 on 2021-02-20 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_boleta_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='media/acta')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Candidato')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Municipio')),
            ],
        ),
        migrations.DeleteModel(
            name='Boleta',
        ),
    ]
