# Generated by Django 2.2 on 2021-02-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210219_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corriente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='corriente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Corriente'),
            preserve_default=False,
        ),
    ]
