# Generated by Django 2.2 on 2021-10-09 15:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20211007_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesa',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='presidente',
        ),
        migrations.RemoveField(
            model_name='mesa',
            name='vocal',
        ),
        migrations.AddField(
            model_name='mesa',
            name='centro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='CentroEducativo', to='main.CentroEducativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesa',
            name='descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='centro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centro_votos', to='main.CentroEducativo'),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 862223)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 9, 9, 42, 20, 877865)),
        ),
        migrations.DeleteModel(
            name='inscripcion',
        ),
    ]
