# Generated by Django 2.2 on 2021-02-20 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_acta_aldea'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoBoleta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TipoBoleta'),
            preserve_default=False,
        ),
    ]
