# Generated by Django 2.2 on 2021-02-20 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210219_2154'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoBoleta',
            new_name='TipoActa',
        ),
        migrations.RenameField(
            model_name='acta',
            old_name='tipo',
            new_name='tipoActa',
        ),
    ]
