# Generated by Django 2.2 on 2021-02-20 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210219_2156'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoActa',
            new_name='Tipo',
        ),
        migrations.RenameField(
            model_name='acta',
            old_name='tipoActa',
            new_name='tipo',
        ),
        migrations.AddField(
            model_name='candidato',
            name='tipo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Tipo'),
            preserve_default=False,
        ),
    ]
