# Generated by Django 2.2 on 2021-02-20 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210219_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=150)),
                ('direccion', models.CharField(max_length=150)),
                ('presidente', models.CharField(max_length=150)),
                ('vocal', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='acta',
            name='mesa',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Mesa'),
            preserve_default=False,
        ),
    ]
