# Generated by Django 2.2 on 2021-02-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210219_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='numero',
            field=models.IntegerField(max_length=150),
        ),
    ]
