# Generated by Django 2.2 on 2021-03-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210219_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblDepartmentsMunicipalities',
            fields=[
                ('id_distrito', models.AutoField(db_column='ID_DISTRITO', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=1000)),
                ('code_real', models.CharField(db_column='CODE_REAL', max_length=4, unique=True)),
                ('id_depto', models.IntegerField(blank=True, db_column='ID_DEPTO', null=True)),
                ('active', models.SmallIntegerField(blank=True, db_column='ACTIVE', null=True)),
            ],
            options={
                'db_table': 'TBL_DEPARTMENTS_MUNICIPALITIES',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblDocument',
            fields=[
                ('id_document', models.AutoField(db_column='ID_DOCUMENT', primary_key=True, serialize=False)),
                ('doc_number', models.CharField(db_column='DOC_NUMBER', max_length=1000)),
                ('b64_doc_code', models.TextField(db_column='B64_DOC_CODE')),
                ('tipo_doc', models.TextField(db_column='TIPO_DOC')),
                ('latitude', models.CharField(db_column='LATITUDE', max_length=1000)),
                ('longitude', models.CharField(db_column='LONGITUDE', max_length=1000)),
                ('create_date', models.DateField(db_column='CREATE_DATE')),
                ('active', models.SmallIntegerField(blank=True, db_column='ACTIVE', null=True)),
            ],
            options={
                'db_table': 'TBL_DOCUMENT',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblPerson',
            fields=[
                ('id_person', models.AutoField(db_column='ID_PERSON', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='NAME', max_length=500)),
                ('id_number', models.CharField(db_column='ID_NUMBER', max_length=500)),
                ('phone', models.CharField(db_column='PHONE', max_length=9)),
                ('create_date', models.DateTimeField(db_column='CREATE_DATE')),
                ('active', models.SmallIntegerField(blank=True, db_column='ACTIVE', null=True)),
            ],
            options={
                'db_table': 'TBL_PERSON',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='corriente',
        ),
    ]
