# Generated by Django 2.2 on 2021-03-11 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210310_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='corriente',
            name='candidato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Candidato'),
            preserve_default=False,
        ),
    ]
