# Generated by Django 2.2 on 2021-10-14 19:43

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0013_auto_20211010_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='centroeducativo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='partido',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='partido',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949)),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 14, 13, 43, 41, 144949))),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipio_usuario', to='main.Municipio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_requests_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_requests_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
