# Generated by Django 2.2 on 2021-03-11 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_corriente_candidato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corriente',
            name='candidato',
        ),
        migrations.AddField(
            model_name='candidato',
            name='corriente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Corriente'),
            preserve_default=False,
        ),
    ]
