# Generated by Django 2.2 on 2021-03-11 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_corriente_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='email',
        ),
        migrations.RemoveField(
            model_name='candidato',
            name='telefono',
        ),
    ]
