# Generated by Django 2.2 on 2021-03-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210311_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='identidad',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
