# Generated by Django 2.2 on 2021-03-12 17:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0018_auto_20210311_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='acta',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='acta',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acta_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='acta_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='aldea',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aldea_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aldea',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='aldea_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='candidato',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidato',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidato_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='corriente',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corriente_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='corriente',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='corriente_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='departamento',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='departamento',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='departamento',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='departamento_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='mesa',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mesa_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mesa',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='mesa_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='municipio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='municipio',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='municipio',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='municipio_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 11, 17, 19, 32810)),
        ),
        migrations.AddField(
            model_name='tipo',
            name='user_created',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_requests_user_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipo',
            name='user_update',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tipo_requests_user_update', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acta',
            name='aldea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Aldea'),
        ),
    ]
