# Generated by Django 2.2 on 2021-03-12 20:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210312_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='acta',
            name='autc_mer_bg',
            field=models.IntegerField(default=0, verbose_name='(+) MIEMBROS MER'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='autc_total_bg',
            field=models.IntegerField(default=0, verbose_name='TOTAL VOTANTES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='autc_v_bg',
            field=models.IntegerField(default=0, verbose_name='CIUDADANOS QUE VOTARON'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='autp_n_bg',
            field=models.IntegerField(default=0, verbose_name='(-) NO UTILIZADAS/SOBRANTES'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='autp_ra_bg',
            field=models.IntegerField(default=0, verbose_name='RECIBIDAS SEGÚN ACTA DE APERTURA'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='acta',
            name='autp_u_bg',
            field=models.IntegerField(default=0, verbose_name='UTILIZADAS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acta',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='acta',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 14, 33, 57, 603826)),
        ),
    ]
