# Generated by Django 2.2 on 2021-03-12 22:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20210312_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='acta',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 12, 16, 51, 2, 531398)),
        ),
    ]
