# Generated by Django 2.2 on 2021-03-13 06:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0025_auto_20210312_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='autc_mer_bg',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='autc_total_bg',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='autc_v_bg',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='autp_n_bg',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='autp_ra_bg',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='autp_u_bg',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='corriente',
        ),
        migrations.AlterField(
            model_name='acta',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='acta',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080)),
        ),
        migrations.CreateModel(
            name='Escrutinio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080))),
                ('tipo', models.CharField(choices=[('C', 'Conteo'), ('VB', 'Votos Blancos'), ('VN', 'Votos Nulos'), ('GT', 'Gran Total')], max_length=3)),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_votacion', to='main.Acta')),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Candidato')),
                ('corriente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Corriente')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrutinio_requests_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrutinio_requests_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalanceGeneral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 0, 8, 3, 910080))),
                ('autp_ra_bg', models.IntegerField(verbose_name='RECIBIDAS SEGÚN ACTA DE APERTURA')),
                ('autp_n_bg', models.IntegerField(verbose_name='(-) NO UTILIZADAS/SOBRANTES')),
                ('autp_u_bg', models.IntegerField(verbose_name='UTILIZADAS')),
                ('autc_v_bg', models.IntegerField(verbose_name='CIUDADANOS QUE VOTARON')),
                ('autc_mer_bg', models.IntegerField(verbose_name='(+) MIEMBROS MER')),
                ('autc_total_bg', models.IntegerField(verbose_name='TOTAL VOTANTES')),
                ('acta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acta_balance', to='main.Acta')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancegeneral_requests_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balancegeneral_requests_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
