# Generated by Django 2.2 on 2021-03-13 21:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_auto_20210313_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='origen',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='user_update',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='update_at',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='municipio',
            name='user_update',
        ),
        migrations.AlterField(
            model_name='acta',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='acta',
            name='mesa',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='acta',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='balancegeneral',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394)),
        ),
        migrations.CreateModel(
            name='inscripcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394))),
                ('update_at', models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 13, 15, 18, 55, 48394))),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Candidato')),
                ('corriente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Corriente')),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_requests_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripcion_requests_user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
