# Generated by Django 2.2 on 2021-03-14 21:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20210314_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='escrutinio',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrutinio',
            name='municipio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Municipio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrutinio',
            name='tipo_escrutinio',
            field=models.CharField(choices=[('C', 'Conteo'), ('VB', 'Votos Blancos'), ('VN', 'Votos Nulos'), ('GT', 'Gran Total')], default=1, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='escrutinio',
            name='valor',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='acta',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='acta',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='corriente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Corriente'),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tipo'),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 3, 14, 15, 4, 38, 955142)),
        ),
    ]
