# Generated by Django 2.2 on 2021-10-07 04:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20211006_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acta',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='user_created',
        ),
        migrations.RemoveField(
            model_name='acta',
            name='user_update',
        ),
        migrations.DeleteModel(
            name='TblDepartmentsMunicipalities',
        ),
        migrations.DeleteModel(
            name='TblPerson',
        ),
        migrations.RemoveField(
            model_name='escrutinio',
            name='acta',
        ),
        migrations.AlterField(
            model_name='aldea',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='aldea',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='corriente',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='escrutinio',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='update_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 10, 6, 22, 14, 1, 642896)),
        ),
        migrations.DeleteModel(
            name='Acta',
        ),
        migrations.DeleteModel(
            name='TblDocument',
        ),
    ]
